[package]
name = "geothelphusa-github-io"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
horrorshow = "0.8.4"

[dependencies]
regex = "1.11.1"
stylist = { version = "0.13.0", features = ["yew_integration"] }
yew = { version = "0.21", features = ["csr"] }
