name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # デプロイするブランチ名

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - name: Install Trunk
        run: cargo install trunk
      - name: Build
        run: cargo build --release # ここで Yew がビルドされる
      - name: Build Web
        run: trunk build --release --public-url /geothelphusa.github.io/ # 実質的デプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist