name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # make dist written rustlang repo

permissions: # 権限 この場合書き込み権限を与えている
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - name: Install Trunk
        run: cargo install trunk
      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown # ここで Yew がビルドされる generate HTML template
      - name: Build Web
        run: trunk build --release --public-url geothelphusa.github.io # 実質的デプロイ overwrite template HTML リポジトリ名がサイトドメインなので/でOK
#      - name: Update index.html with correct JS file
#        run: cargo run --release --bin update_index
#      - name: Rename to app.js
#        run: mv dist/geothelphusa-github-io-*.js dist/app.js
      - name: Check dist directory
        run: ls -l dist
#      - name: Delete integrity
#        run: sed -i 's/integrity="[^"]*"//g' dist/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          force_orphan: true # `gh-pages` ブランチをリセットしてクリーンにデプロイ